/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mart01;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi01.koneksi01;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.awt.Font;



/**
 *
 * @author TEGAR RASYID
 */
public class mart02 extends javax.swing.JFrame {
    private DefaultTableModel model;
    int subTotalBelanja, baris, jumlahBaris;
    DefaultTableModel dataModel, dataModel1;
    private boolean barisTerpilih;

    private void enabled(){
        txtIdBarang.setEnabled(false);
        txtHarga.setEnabled(false);
        txtJmlHarga.setEnabled(false);
        txthargabarang.setEnabled(true);
        txtjmlbarang.setEnabled(true);
        tblTampilDataBarang.requestFocus();
    }
    
    
    
    private void datatable(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Barang");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Harga Barang");
        tblTampilDataBarang.setModel(tbl);
         try{
             
             Statement stat3 = (Statement) koneksi01.getKoneksi().createStatement( );
             ResultSet res3 = stat3.executeQuery("select * from barang");
             while(res3.next())
             {
                 tbl.addRow(new Object[] {
                     res3.getString("id_barang"),
                     res3.getString("nama_barang"),
                     res3.getString("Harga_barang"),
                 });
                 tblTampilDataBarang.setModel(tbl);
             }
         }catch (Exception e){
             JOptionPane.showMessageDialog(rootPane, "salah");
         }
    }
    
    
    
    private void desabled(){
        
        txtIdBarang.enable(true);
        cmbBarang.enable(true);
        txtHarga.enable(true);
        txtJmlHarga.enable(true);
        txthargabarang.setEnabled(false);
        txtjmlbarang.setEnabled(false);
        
    }
    
    
    /**
     * Creates new form mart02
     */
    public mart02() {
        initComponents();
        datatable();
        getcombo();
        enabled();
        dataModel = (DefaultTableModel) tblBarang.getModel();
        tblBarang.getTableHeader().setFont(new Font("Sanserif", Font.CENTER_BASELINE,14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbBarang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJmlHarga = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTampilDataBarang = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txthargabarang = new javax.swing.JTextField();
        txtjmlbarang = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        btnEdit2 = new javax.swing.JButton();
        btndelete2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Pilih Barang :");

        cmbBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBarangItemStateChanged(evt);
            }
        });
        cmbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarangActionPerformed(evt);
            }
        });

        jLabel2.setText("Rp :");

        jLabel4.setText("Jumlah :");

        txtJmlHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlHargaActionPerformed(evt);
            }
        });
        txtJmlHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJmlHargaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJmlHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtJmlHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("Rp :");

        lblTotalHarga.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTotalHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalHarga.setText("Total");
        lblTotalHarga.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        tblTampilDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTampilDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTampilDataBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTampilDataBarang);

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga Satuan", "Jumlah Beli", "Sub Total"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBarang);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("ID BARANG       :");

        jLabel6.setText("NAMA BARANG :");

        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });

        jLabel5.setText("HARGA BARANG :");

        jLabel8.setText("JUMLAH BARANG :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaBarang)))
                .addGap(140, 140, 140)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txthargabarang)
                    .addComponent(txtjmlbarang, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txthargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtjmlbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btntambah.setText("Tambah");
        btntambah.setPreferredSize(new java.awt.Dimension(75, 23));
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnEdit2.setText("Edit");

        btndelete2.setText("Delete");
        btndelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btndelete2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndelete2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEdit.setText("Edit Jual");
        btnEdit.setPreferredSize(new java.awt.Dimension(65, 23));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btndelete.setText("Deleten Jual");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        simpan.setText("Jual");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan))
                .addGap(18, 18, 18)
                .addComponent(btndelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clear))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(clear)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJmlHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlHargaActionPerformed

    private void cmbBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBarangItemStateChanged
        // TODO add your handling code here:
//        switch (cmbBarang.getSelectedIndex()){
//            case 0:
//            lblHarga.setText("Pilih Barang");
//            break;
//            case 1:
//            lblHarga.setText("4000");
//            break;
//            case 2:
//            lblHarga.setText("3000");
//            break;
//            case 3:
//            lblHarga.setText("5000");
//            break;
//            case 4:
//            lblHarga.setText("3500");
//            break;
//            case 5:
//            lblHarga.setText("7000");
//            break;
//            default:
//                lblHarga.setText("OK");
//        }
//        txtHarga.setText("");
//        txtHarga.requestFocus();
        
        
        gettext();
       
        desabled();
        
    }//GEN-LAST:event_cmbBarangItemStateChanged

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int baris =  tblBarang.getSelectedRow();
dataModel.removeRow(baris);
total();
clear();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        isidata();
    }//GEN-LAST:event_btntambahActionPerformed

    private void txtJmlHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlHargaKeyPressed
        // TODO add your handling code here:
        
        List baris = new ArrayList<>();
        tblBarang.setAutoCreateColumnsFromModel(true);
        baris.add(cmbBarang.getSelectedItem().toString());
        baris.add(txtHarga.getText());
        baris.add(txtJmlHarga.getText());
        
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(barisTerpilih){
                btnEditClick();
            }else{
              subTotal();
            baris.add(String.valueOf(subTotalBelanja));
            dataModel.addRow(baris.toArray());
            
            total();
            clear();  
            }  
        }
        if (evt.getKeyCode() == KeyEvent.VK_DELETE){
            if (barisTerpilih){
                KeyDelete();
            }
            tblBarang.clearSelection();
            barisTerpilih = false;
        }
    }//GEN-LAST:event_txtJmlHargaKeyPressed

    private void tblTampilDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTampilDataBarangMouseClicked
        // TODO add your handling code here:                                               
        baris = tblTampilDataBarang.getSelectedRow();
        if(baris >= 0){
        barisTerpilih = true;
        String namaBarang = (String) tblTampilDataBarang.getValueAt(baris, 0);
        String hargaSatuan = (String) tblTampilDataBarang.getValueAt(baris, 1);
        String jumlahBeli = (String) tblTampilDataBarang.getValueAt(baris, 2);
        
        cmbBarang.setSelectedItem(namaBarang);
        txtHarga.setText(hargaSatuan);
        txtJmlHarga.setText(jumlahBeli);
        
        
        }else {
            barisTerpilih = false;
        }
    }//GEN-LAST:event_tblTampilDataBarangMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        btnEditClick();
        total();
        clear();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
//        baris = tblBarang.getSelectedRow();
//        if(baris >= 0){
//        barisTerpilih = true;
//        String namaBarang = (String) tblBarang.getValueAt(baris, 0);
//        String hargaSatuan = (String) tblBarang.getValueAt(baris, 1);
//        String jumlahBeli = (String) tblBarang.getValueAt(baris, 2);
//        
//        cmbBarang.setSelectedItem(namaBarang);
//        lblHarga.setText(hargaSatuan);
//        txtHarga.setText(jumlahBeli);
//        }else {
//            barisTerpilih = false;
//        }


        baris = tblBarang.getSelectedRow();
        if(baris >= 0){
        barisTerpilih = true;
        String namaBarang = (String) tblBarang.getValueAt(baris, 0);
        String hargaSatuan = (String) tblBarang.getValueAt(baris, 1);
        String jumlahBeli = (String) tblBarang.getValueAt(baris, 2); 
        
        
        cmbBarang.setSelectedItem(namaBarang);
        txtHarga.setText(hargaSatuan);
        txtJmlHarga.setText(jumlahBeli);
       
        }else {
            barisTerpilih = false;
            
        }
    }//GEN-LAST:event_tblBarangMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        cmbBarang.setSelectedItem(0);
        txtHarga.setText("");
        lblTotalHarga.setText("");
        txtJmlHarga.setText("");
        txtIdBarang.setText("");
        txtNamaBarang.setText("");
        DefaultTableModel modell = (DefaultTableModel) tblBarang.getModel();
        dataModel.setRowCount(0);
        total();
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void btndelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete2ActionPerformed
        // TODO add your handling code here:
        int baris =  tblTampilDataBarang.getSelectedRow();
dataModel1.removeRow(baris);
total();
clear();
    }//GEN-LAST:event_btndelete2ActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
        enabled();
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void cmbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mart02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mart02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mart02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mart02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mart02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit2;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelete2;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblTampilDataBarang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtJmlHarga;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txthargabarang;
    private javax.swing.JTextField txtjmlbarang;
    // End of variables declaration//GEN-END:variables

private void getcombo() {
         try{
            Statement stat3 = (Statement) koneksi01.getKoneksi().createStatement( );
            String sql3 = "Select * from barang";
            ResultSet res3 = stat3.executeQuery(sql3);
            cmbBarang.addItem("-Pilih Nama Barang");
            while(res3.next())
            {
                
                cmbBarang.addItem(res3.getString("nama_barang"));
            }
        }catch (SQLException ex){
//            Longger.getLongger(FromGaji.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void gettext() {
        String nama_barang = (String) cmbBarang.getSelectedItem();
        try{
            Statement stat3 = (Statement) koneksi01.getKoneksi().createStatement( );
            String sql3 = "Select * from barang where nama_barang='"+nama_barang+"'";
            ResultSet res3 = stat3.executeQuery(sql3);
            while(res3.next())

            {
                txtHarga.setText((String)res3.getString("harga_barang"));
                txtNamaBarang.setText((String)res3.getString("nama_barang"));
                txtIdBarang.setText((String)res3.getString("id_barang"));

            }
        }catch (SQLException ex){
//            Longger.getLongger(FromGaji.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clear() {
        txtHarga.setText("");
        txtNamaBarang.setText("");
        txtIdBarang.setText("");
        cmbBarang.setSelectedIndex(0);
        btntambah.setText("Simpan");
        txthargabarang.setText("");
        txtjmlbarang.setText("");

    }


//    private void datatable(){
//        DefaultTableModel tbl = new DefaultTableModel();
//        tbl.addColumn("ID Barang");
//        tbl.addColumn("Nama Barang");
//        tbl.addColumn("Harga Barang");
//        tblTampilDataBarang.setModel(tbl);
//         try{
//             
//             Statement stat3 = (Statement) koneksi01.getKoneksi().createStatement( );
//             ResultSet res3 = stat3.executeQuery("select * from barang");
//             while(res3.next())
//             {
//                 tbl.addRow(new Object[] {
//                     res3.getString("id_barang"),
//                     res3.getString("nama_barang"),
//                     res3.getString("Harga_barang"),
//                 });
//                 tblTampilDataBarang.setModel(tbl);
//             }
//         }catch (Exception e){
//             JOptionPane.showMessageDialog(rootPane, "salah");
//         }
//    }


    private void isidata() {
    if (btntambah.getText()== "TAMBAH") {
        enabled();
        clear();
//        desabled();
        btntambah.setText("Simpan");
        btndelete.setEnabled(false);
        btnEdit.setEnabled(false);

        
    } else {
        String nama_barang = txtNamaBarang.getText();
        String harga_barang = txthargabarang.getText();
        String jumlah_Barang = txtjmlbarang.getText();
        
        
        try {
            Statement statement = (Statement) koneksi01.getKoneksi().createStatement();
            String sql = "INSERT INTO barang (nama_barang, harga_barang) VALUES ('" + nama_barang + "', " + harga_barang + ")";
            statement.executeUpdate(sql);
            statement.close();
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            datatable();
            clear();
            btntambah.setText("Tambah");
            
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan " );
        }
    }
}
    
    
    
  
    
    
    
    
    
    private int subTotal (){
        int jumlahBeli, hargaSatuan;
        jumlahBeli = Integer.valueOf(txtJmlHarga.getText());
        hargaSatuan = Integer.valueOf(txtHarga.getText());
        subTotalBelanja = jumlahBeli*hargaSatuan;
        return subTotalBelanja;
        
    }

    
    private void total() {
        int jumlah = dataModel.getRowCount();
        int sumTotal = 0;
        for (int i = 0 ; i < jumlah; i++){
            int dataTotal = Integer.valueOf(dataModel.getValueAt(i,3).toString());
            sumTotal += dataTotal;
        }
        lblTotalHarga.setText(Integer.toString(sumTotal));
    }
    
    
    private void btnEditClick() {
        //cekbaristerpilih
        String nmBarang = (String) cmbBarang.getSelectedItem();
        String hrgSatuan = (String) txtHarga.getText ();
        String jmlBeli = (String) txtJmlHarga.getText();
        
        subTotal();
        dataModel.setValueAt(nmBarang, baris, 0);
        dataModel.setValueAt(hrgSatuan, baris, 1);
        dataModel.setValueAt(jmlBeli, baris, 2);
        dataModel.setValueAt(subTotalBelanja, baris, 3);
        
        clear();
        total();
        tblBarang.clearSelection();
        barisTerpilih=false;
    }

    
    private int jumlahBarisTable(){
        jumlahBaris =tblBarang.getRowCount();
        return jumlahBaris;
    }
    
    private boolean cekBarisTerpilih(){
        return true;
    }

    private void KeyDelete() {
        baris = tblBarang.getSelectedRow();
        barisTerpilih=true;
        dataModel.removeRow(baris);
        
        total();
        clear();
        barisTerpilih=false;
    }
    
    
    
    
    
    
//    private void enabled1(){
//        txtNamaBarang.enable(true);
//        txtjmlharga.enable(true);
//        txtjmlbeli.enable(true);
//        txtNamaBarang.requestFocus();
//    }
//    
//    
//    private void desabled1(){
//        txtIdBarang.enable(false);
//        cmbBarang.enable(false);
//        txtHarga.enable(false);
//        txtJmlHarga.enable(false);
//    }
    
    

    
    
    
    
    
    
    
//    private void btnEditClick1() {
//        //cekbaristerpilih
//        String nmBarang = (String) cmbBarang.getSelectedItem();
//        String hrgSatuan = (String) txtHarga.getText ();
//        String jmlBeli = (String) txtJmlHarga.getText();
//        
//        subTotal();
//        dataModel1.setValueAt(nmBarang, baris, 0);
//        dataModel1.setValueAt(hrgSatuan, baris, 1);
//        dataModel1.setValueAt(jmlBeli, baris, 2);
//        dataModel1.setValueAt(subTotalBelanja, baris, 3);
//        
//        clear();
//        total();
//        tblTampilDataBarang.clearSelection();
//        barisTerpilih=false;
//    }
}
