/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toko001;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi01.koneksi001;

/**
 *
 * @author TEGAR RASYID
 */
public class Toko001 extends javax.swing.JFrame {
private DefaultTableModel model;

    /**
     * Creates new form Toko001
     */
    public Toko001() {
        initComponents();
         datatable();
        getcombo();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbBarang = new javax.swing.JComboBox<>();
        txtNilaiPBO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNamaSiswa = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTampilDataBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Siswa :");

        cmbBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBarangItemStateChanged(evt);
            }
        });
        cmbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarangActionPerformed(evt);
            }
        });

        txtNilaiPBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilaiPBOActionPerformed(evt);
            }
        });

        jLabel2.setText("Nana Siswa");

        jLabel3.setText("Nilai PBO");

        txtNamaSiswa.setText(" ");

        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tblTampilDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTampilDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTampilDataBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTampilDataBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNilaiPBO, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnTambah)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNilaiPBO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah)
                    .addComponent(txtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBarangItemStateChanged
        // TODO add your handling code here:
//        int nilai1=70;
//        int nilai2=90;
//        String nmSiswa;
//        nmSiswa = (String)cmbBarang.getSelectedItem();
//        if(nmSiswa.equals("siswa01")){
//            txtNilaiPBO.setText(String.valueOf(nilai1));
//        }else{
//            txtNilaiPBO.setText(String.valueOf(nilai2));
//        }
//        txtNilaiPBO.setText(nmSiswa);
            
        gettext();
    }//GEN-LAST:event_cmbBarangItemStateChanged

    private void txtNilaiPBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiPBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiPBOActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        isidata();
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblTampilDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTampilDataBarangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblTampilDataBarangMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
//        isidata();
    }//GEN-LAST:event_btnTambahMouseClicked

    private void cmbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toko001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toko001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toko001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toko001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toko001().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTampilDataBarang;
    private javax.swing.JTextField txtNamaSiswa;
    private javax.swing.JTextField txtNilaiPBO;
    // End of variables declaration//GEN-END:variables

    private void getcombo() {
         try{
            Statement stat3 = (Statement) koneksi001.getKoneksi().createStatement( );
            String sql3 = "Select * from crud01";
            ResultSet res3 = stat3.executeQuery(sql3);
            cmbBarang.addItem("-Pilih Nama Siswa");
            while(res3.next())
            {
                
                cmbBarang.addItem(res3.getString("nama_siswa"));
            }
        }catch (SQLException ex){
//            Longger.getLongger(FromGaji.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void gettext() {
        String nama_siswa = (String) cmbBarang.getSelectedItem();
        try{
            Statement stat3 = (Statement) koneksi001.getKoneksi().createStatement( );
            String sql3 = "Select * from crud01 where nama_siswa='"+nama_siswa+"'";
            ResultSet res3 = stat3.executeQuery(sql3);
            while(res3.next())
            {
                txtNilaiPBO.setText((String)res3.getString("nilai_pbo"));
                txtNamaSiswa.setText((String)res3.getString("nama_siswa"));
            }
        }catch (SQLException ex){
//            Longger.getLongger(FromGaji.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clear() {
        txtNilaiPBO.setText("");
        txtNamaSiswa.setText("");
        cmbBarang.setSelectedIndex(0);
//        btnTambah.setText("Simpan");

    }


    private void datatable(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NISN");
        tbl.addColumn("Nama Siswa");
        tbl.addColumn("Nilai PBO");
        tblTampilDataBarang.setModel(tbl);
         try{
             
             Statement stat3 = (Statement) koneksi001.getKoneksi().createStatement( );
             ResultSet res3 = stat3.executeQuery("select * from crud01");
             while(res3.next())
             {
                 tbl.addRow(new Object[] {
                     res3.getString("nisn"),
                     res3.getString("nama_siswa"),
                     res3.getString("nilai_pbo"),
                 });
                 tblTampilDataBarang.setModel(tbl);
             }
         }catch (Exception e){
             JOptionPane.showMessageDialog(rootPane, "salah");
         }
    }

    private void isidata() {
    if (btnTambah.getText().equals("TAMBAH")) {
        clear();
    } else {
        String nama_siswa = txtNamaSiswa.getText();
        String nilai_pbo = txtNilaiPBO.getText();
        
        try {
            Statement statement = (Statement) koneksi001.getKoneksi().createStatement();
            String sql = "INSERT INTO crud01 (nama_siswa, nilai_pbo) VALUES ('" + nama_siswa + "', " + nilai_pbo + ")";
            statement.executeUpdate(sql);
            statement.close();
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            datatable();
            clear();
            btnTambah.setText("Tambah");
            
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + t.getMessage());
        }
    }
}
    
    
}

