/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devault;

/**
 *
 * @author TEGAR RASYID
 */
public class PengalihanJalur extends javax.swing.JFrame {

    
    public String bilangan= " ";
    public String bilangan1= " ";
    public int pilih;
    public double num1,num2,result;
    private int mundur,panjangString;
    int start;
    /**
     * Creates new form PengalihanJalur
     */
    public PengalihanJalur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clear = new javax.swing.JButton();
        tbl1 = new javax.swing.JButton();
        tbl2 = new javax.swing.JButton();
        tbljml = new javax.swing.JButton();
        tblhsl = new javax.swing.JButton();
        layaratas = new javax.swing.JLabel();
        tblkrg = new javax.swing.JButton();
        layarbawah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        tbl1.setText("1");
        tbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl1ActionPerformed(evt);
            }
        });

        tbl2.setText("2");
        tbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl2ActionPerformed(evt);
            }
        });

        tbljml.setText("+");
        tbljml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbljmlActionPerformed(evt);
            }
        });

        tblhsl.setText("=");
        tblhsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblhslActionPerformed(evt);
            }
        });

        layaratas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        tblkrg.setText("-");
        tblkrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkrgActionPerformed(evt);
            }
        });

        layarbawah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        layarbawah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl1)
                    .addComponent(clear)
                    .addComponent(tbl2))
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblhsl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbljml)
                                .addGap(35, 35, 35)
                                .addComponent(tblkrg)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(layarbawah, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)))
                    .addComponent(layaratas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(layaratas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layarbawah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbl2)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbl1)
                    .addComponent(tbljml)
                    .addComponent(tblkrg))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(tblhsl))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblhslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblhslActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            num2 = Double.parseDouble(String.valueOf(layarbawah.getText()));
            result = num1+num2;
            bilangan = Double.toString(result);            
            break;
        case 2:
            num2 = Double.parseDouble(String.valueOf(layarbawah.getText()));
            result = num1-num2;
            bilangan = Double.toString(result);            
            break;
        case 3:
            num2 = Double.parseDouble(String.valueOf(layarbawah.getText()));
            result = num1*num2;
            bilangan = Double.toString(result);            
            break;
        case 4:
            num2 = Double.parseDouble(String.valueOf(layarbawah.getText()));
            result = num1/num2;
            bilangan = Double.toString(result);            
            break;
        
        default:
            break;       
        
    }                                      
        layarbawah.setText(bilangan);
        layaratas.setText(bilangan1+"=");
        start=1;
    }//GEN-LAST:event_tblhslActionPerformed

    private void tbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl2ActionPerformed
        // TODO add your handling code here:
          bilangan +="2";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "2";
    }//GEN-LAST:event_tbl2ActionPerformed

    private void tbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl1ActionPerformed
        // TODO add your handling code here:
       bilangan +="1";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "1";
    }//GEN-LAST:event_tbl1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
       clear();
    }//GEN-LAST:event_clearActionPerformed

    private void tbljmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbljmlActionPerformed
        // TODO add your handling code here:
        num1=Double.parseDouble(bilangan);
        bilangan1=bilangan1+"+";
        layarbawah.setText("+");
        layaratas.setText(bilangan1);
        bilangan=" ";
        pilih=1;
    }//GEN-LAST:event_tbljmlActionPerformed

    private void tblkrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkrgActionPerformed
        // TODO add your handling code here:
       num1=Double.parseDouble(bilangan);
        layarbawah.setText("-");
        layaratas.setText(bilangan1);
        bilangan=" ";
        pilih=2;
    }//GEN-LAST:event_tblkrgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengalihanJalur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengalihanJalur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengalihanJalur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengalihanJalur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengalihanJalur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JLabel layaratas;
    private javax.swing.JLabel layarbawah;
    private javax.swing.JButton tbl1;
    private javax.swing.JButton tbl2;
    private javax.swing.JButton tblhsl;
    private javax.swing.JButton tbljml;
    private javax.swing.JButton tblkrg;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        bilangan="";
        bilangan1="";
        layarbawah.setText("");
        layaratas.setText("");
        layarbawah.setText("0");
    }

    private int mundur() {
       panjangString=bilangan.length();
       mundur=panjangString - 1;
       layarbawah.setText(String.valueOf(bilangan.substring(0, mundur)));
       bilangan=layarbawah.getText();
       if(bilangan.length()<1){
           layarbawah.setText("0");
       }
       return panjangString;
    }
    
}
