/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sourcecode2;

/**
 *
 * @author TEGAR RASYID
 */
public class Kalkulator extends javax.swing.JFrame {

    public String bilangan= " ";
    public String bilangan1= " ";
    public int pilih;
    public double num1,num2,result;
    private int mundur,panjangString;
    int start;
    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbl4 = new javax.swing.JButton();
        layaratas = new javax.swing.JLabel();
        tblhsl = new javax.swing.JButton();
        tbl0 = new javax.swing.JButton();
        tbl5 = new javax.swing.JButton();
        tblkoma = new javax.swing.JButton();
        tbl7 = new javax.swing.JButton();
        tblbg = new javax.swing.JButton();
        layarbawah = new javax.swing.JLabel();
        tbl6 = new javax.swing.JButton();
        tblkl = new javax.swing.JButton();
        tblhps = new javax.swing.JButton();
        tbl8 = new javax.swing.JButton();
        tbl1 = new javax.swing.JButton();
        tblkrg = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        tbl9 = new javax.swing.JButton();
        tbl2 = new javax.swing.JButton();
        tbljml = new javax.swing.JButton();
        tbl3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl4.setText("4");
        tbl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl4ActionPerformed(evt);
            }
        });

        layaratas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        tblhsl.setText("=");
        tblhsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblhslActionPerformed(evt);
            }
        });

        tbl0.setText("0");
        tbl0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl0ActionPerformed(evt);
            }
        });

        tbl5.setText("5");
        tbl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl5ActionPerformed(evt);
            }
        });

        tblkoma.setText(",");
        tblkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkomaActionPerformed(evt);
            }
        });

        tbl7.setText("7");
        tbl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl7ActionPerformed(evt);
            }
        });

        tblbg.setText("÷");
        tblbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblbgActionPerformed(evt);
            }
        });

        layarbawah.setBackground(new java.awt.Color(153, 153, 153));
        layarbawah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        layarbawah.setText("0");
        layarbawah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl6.setText("6");
        tbl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl6ActionPerformed(evt);
            }
        });

        tblkl.setText("x");
        tblkl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblklActionPerformed(evt);
            }
        });

        tblhps.setText("←");
        tblhps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblhpsActionPerformed(evt);
            }
        });

        tbl8.setText("8");
        tbl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl8ActionPerformed(evt);
            }
        });

        tbl1.setText("1");
        tbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl1ActionPerformed(evt);
            }
        });

        tblkrg.setText("-");
        tblkrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblkrgActionPerformed(evt);
            }
        });

        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        tbl9.setText("9");
        tbl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl9ActionPerformed(evt);
            }
        });

        tbl2.setText("2");
        tbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl2ActionPerformed(evt);
            }
        });

        tbljml.setText("+");
        tbljml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbljmlActionPerformed(evt);
            }
        });

        tbl3.setText("3");
        tbl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl3ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Scentific");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layarbawah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(layaratas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbl9, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(tbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbl0, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblkoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblhps, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tblkl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblkrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbljml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblhsl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblbg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(layaratas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layarbawah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblhps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblkl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblkrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbljml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblkoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblhsl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl4ActionPerformed
        // TODO add your handling code here:
        bilangan +="4";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "4";
            
            if (start == 1){
                clear();
                bilangan += "4";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "4";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl4ActionPerformed

    private void tblhslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblhslActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            num2 = Double.parseDouble(String.valueOf(layarbawah.getText()));
            result = num1+num2;
            bilangan = Double.toString(result);            
            break;
        case 2:
            num2 = Double.parseDouble(String.valueOf(layarbawah.getText()));
            result = num1-num2;
            bilangan = Double.toString(result);            
            break;
        case 3:
            num2 = Double.parseDouble(String.valueOf(layarbawah.getText()));
            result = num1*num2;
            bilangan = Double.toString(result);            
            break;
        case 4:
            num2 = Double.parseDouble(String.valueOf(layarbawah.getText()));
            result = num1/num2;
            bilangan = Double.toString(result);            
            break;
        
        default:
            break;       
        
    }                                      
        layarbawah.setText(bilangan);
        layaratas.setText(bilangan1+"=");
        start=1;
        
        bilangan = "";
        
        
    }//GEN-LAST:event_tblhslActionPerformed

    private void tbl0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl0ActionPerformed
        // TODO add your handling code here:
        bilangan +="0";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "0";
            
            if (start == 1){
                clear();
                bilangan += "0";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "0";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl0ActionPerformed

    private void tbl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl5ActionPerformed
        // TODO add your handling code here:
        bilangan +="5";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "5";
            
            if (start == 1){
                clear();
                bilangan += "5";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "5";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl5ActionPerformed

    private void tblkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkomaActionPerformed
        // TODO add your handling code here:
        bilangan +=",";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + ",";
    }//GEN-LAST:event_tblkomaActionPerformed

    private void tbl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl7ActionPerformed
        // TODO add your handling code here:
         bilangan +="7";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "7";
            
            if (start == 1){
                clear();
                bilangan += "7";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "7";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl7ActionPerformed

    private void tblbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblbgActionPerformed
        // TODO add your handling code here:
        num1=Double.parseDouble(bilangan);
        bilangan1=bilangan1+"÷";
        layarbawah.setText("÷");
        layaratas.setText(bilangan1);
        bilangan=" ";
        pilih=4;
    }//GEN-LAST:event_tblbgActionPerformed

    private void tbl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl6ActionPerformed
        // TODO add your handling code here:
        bilangan +="6";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "6";
            
            if (start == 1){
                clear();
                bilangan += "6";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "6";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl6ActionPerformed

    private void tblklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblklActionPerformed
        // TODO add your handling code here:
         num1=Double.parseDouble(bilangan);
         bilangan1=bilangan1+"x";
        layarbawah.setText("x");
        layaratas.setText(bilangan1);
        bilangan=" ";
        pilih=3;
    }//GEN-LAST:event_tblklActionPerformed

    private void tblhpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblhpsActionPerformed
        // TODO add your handling code here:
         mundur();

    }//GEN-LAST:event_tblhpsActionPerformed

    private void tbl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl8ActionPerformed
        // TODO add your handling code here:
        bilangan +="8";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "8";
            
            if (start == 1){
                clear();
                bilangan += "8";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "8";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl8ActionPerformed

    private void tbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl1ActionPerformed
        // TODO add your handling code here:
        bilangan +="1";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "1";
            
            if (start == 1){
                clear();
                bilangan += "1";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "1";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl1ActionPerformed

    private void tblkrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblkrgActionPerformed
        // TODO add your handling code here:
        num1=Double.parseDouble(bilangan);
        bilangan1=bilangan1+"-";
        layarbawah.setText("-");
        layaratas.setText(bilangan1);
        bilangan=" ";
        pilih=2;
    }//GEN-LAST:event_tblkrgActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void tbl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl9ActionPerformed
        // TODO add your handling code here:
         bilangan +="9";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "9";
            
            if (start == 1){
                clear();
                bilangan += "9";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "9";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl9ActionPerformed

    private void tbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl2ActionPerformed
        // TODO add your handling code here:
         bilangan +="2";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "2";
            
            if (start == 1){
                clear();
                bilangan += "2";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "2";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl2ActionPerformed

    private void tbljmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbljmlActionPerformed
        // TODO add your handling code here:
        num1=Double.parseDouble(bilangan);
        bilangan1=bilangan1+"+";
        layarbawah.setText("+");
        layaratas.setText(bilangan1);
        bilangan=" ";
        pilih=1;
    }//GEN-LAST:event_tbljmlActionPerformed

    private void tbl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl3ActionPerformed
        // TODO add your handling code here:
         bilangan +="3";
            layarbawah.setText(bilangan);
            bilangan1 = bilangan1 + "3";
            
            if (start == 1){
                clear();
                bilangan += "3";
                layarbawah.setText(bilangan);
                bilangan1 = bilangan + "3";
            }
            else{
                
            }
            start = 0;
    }//GEN-LAST:event_tbl3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel layaratas;
    private javax.swing.JLabel layarbawah;
    private javax.swing.JButton tbl0;
    private javax.swing.JButton tbl1;
    private javax.swing.JButton tbl2;
    private javax.swing.JButton tbl3;
    private javax.swing.JButton tbl4;
    private javax.swing.JButton tbl5;
    private javax.swing.JButton tbl6;
    private javax.swing.JButton tbl7;
    private javax.swing.JButton tbl8;
    private javax.swing.JButton tbl9;
    private javax.swing.JButton tblbg;
    private javax.swing.JButton tblhps;
    private javax.swing.JButton tblhsl;
    private javax.swing.JButton tbljml;
    private javax.swing.JButton tblkl;
    private javax.swing.JButton tblkoma;
    private javax.swing.JButton tblkrg;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        bilangan="";
        bilangan1="";
        layarbawah.setText("");
        layaratas.setText("");
        layarbawah.setText("0");
    }

    private int mundur() {
       panjangString=bilangan.length();
       mundur=panjangString - 1;
       layarbawah.setText(String.valueOf(bilangan.substring(0, mundur)));
       bilangan=layarbawah.getText();
       if(bilangan.length()<1){
           layarbawah.setText("0");
       }
       return panjangString;
    }

}
