/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imegas;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
/**
 *
 * @author TEGAR RASYID
 */
public class kasir extends javax.swing.JFrame {

    int subTotalBelanja, baris, jumlahBaris;
    DefaultTableModel dataModel;
    private boolean barisTerpilih;
    /**
     * Creates new form video
     */
    public kasir() {
        initComponents();
        dataModel = (DefaultTableModel) tblBarang.getModel();
        tblBarang.getTableHeader().setFont(new Font("Sanserif", Font.CENTER_BASELINE,14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbBarang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        txtHarga = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblHarga = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama Barang : ");

        cmbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang....", "Masako", "Ice Creame", "Sampo", "Sabun", "Sikat Gigi" }));
        cmbBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBarangItemStateChanged(evt);
            }
        });

        jLabel3.setText("RP.");

        jLabel4.setText("Jumlah :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("RP.");

        lblTotalHarga.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTotalHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalHarga.setText("Total");

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga Satuan", "Jumlah Beli", "Sub Tolal"
            }
        ));
        tblBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBarang);

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHargaKeyPressed(evt);
            }
        });

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblHarga.setText("Harga");

        jButton1.setText("C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smegamart.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarga))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        /*baris = tblBarang.getSelectedRow();
        String nmBarang = (String) cmbBarang.getSelectedItem();
        String hrgBarang = (String) lblHarga.getText();
        String jmlBeli = (String) txtHarga.getText();
        
        subTotal();        
        dataModel.setValueAt (nmBarang, baris, 0);
        dataModel.setValueAt (hrgBarang, baris, 1);
        dataModel.setValueAt (jmlBeli, baris, 2);
        dataModel.setValueAt (subTotalBelanja, baris, 3);

        tblBarang.clearSelection();
        barisTerpilih=false;*/
        
        btnEditClick();
        total();
        clear();
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        baris = tblBarang.getSelectedRow();
        if(baris >= 0){
        barisTerpilih = true;
        String namaBarang = (String) tblBarang.getValueAt(baris, 0);
        String hargaSatuan = (String) tblBarang.getValueAt(baris, 1);
        String jumlahBeli = (String) tblBarang.getValueAt(baris, 2);
        
        cmbBarang.setSelectedItem(namaBarang);
        lblHarga.setText(hargaSatuan);
        txtHarga.setText(jumlahBeli);
        }else {
            barisTerpilih = false;
        }
    }//GEN-LAST:event_tblBarangMouseClicked

    private void cmbBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBarangItemStateChanged
        // TODO add your handling code here:
        switch (cmbBarang.getSelectedIndex()){
            case 0:
            lblHarga.setText("Pilih Barang");
            break;
            case 1:
            lblHarga.setText("4000");
            break;
            case 2:
            lblHarga.setText("3000");
            break;
            case 3:
            lblHarga.setText("5000");
            break;
            case 4:
            lblHarga.setText("3500");
            break;
            case 5:
            lblHarga.setText("7000");
            break;
            default:
                lblHarga.setText("OK");
        }
        txtHarga.setText("");
        txtHarga.requestFocus();
    }//GEN-LAST:event_cmbBarangItemStateChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris =  tblBarang.getSelectedRow();
dataModel.removeRow(baris);
total();
clear();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyPressed
        // TODO add your handling code here:
        List baris = new ArrayList<>();
        tblBarang.setAutoCreateColumnsFromModel(true);
        baris.add(cmbBarang.getSelectedItem().toString());
        baris.add(lblHarga.getText());
        baris.add(txtHarga.getText());
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(barisTerpilih){
                btnEditClick();
            }else{
              subTotal();
            baris.add(String.valueOf(subTotalBelanja));
            dataModel.addRow(baris.toArray());
            
            total();
            clear();  
            }  
        }
        if (evt.getKeyCode() == KeyEvent.VK_DELETE){
            if (barisTerpilih){
                KeyDelete();
            }
            tblBarang.clearSelection();
            barisTerpilih = false;
        }
    }//GEN-LAST:event_txtHargaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cmbBarang.setSelectedItem(0);
        lblHarga.setText("");
        lblTotalHarga.setText("");
        txtHarga.setText("");
        DefaultTableModel modell = (DefaultTableModel) tblBarang.getModel();
        dataModel.setRowCount(0);
        total();
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtHarga;
    // End of variables declaration//GEN-END:variables

    private int subTotal (){
        int jumlahBeli, hargaSatuan;
        jumlahBeli = Integer.valueOf(txtHarga.getText());
        hargaSatuan = Integer.valueOf(lblHarga.getText());
        subTotalBelanja = jumlahBeli*hargaSatuan;
        return subTotalBelanja;
        
    }

    
    private void total() {
        int jumlah = dataModel.getRowCount();
        int sumTotal = 0;
        for (int i = 0 ; i < jumlah; i++){
            int dataTotal = Integer.valueOf(dataModel.getValueAt(i,3).toString());
            sumTotal += dataTotal;
        }
        lblTotalHarga.setText(Integer.toString(sumTotal));
    }
    
    private void clear(){
        txtHarga.setText("");
        lblHarga.setText("");
        cmbBarang.setSelectedIndex(0);
    }

    private void btnEditClick() {
        //cekbaristerpilih
        String nmBarang = (String) cmbBarang.getSelectedItem();
        String hrgSatuan = (String) lblHarga.getText ();
        String jmlBeli = (String) txtHarga.getText();
        
        subTotal();
        dataModel.setValueAt(nmBarang, baris, 0);
        dataModel.setValueAt(hrgSatuan, baris, 1);
        dataModel.setValueAt(jmlBeli, baris, 2);
        dataModel.setValueAt(subTotalBelanja, baris, 3);
        
        clear();
        total();
        tblBarang.clearSelection();
        barisTerpilih=false;
    }
    
    private int jumlahBarisTable(){
        jumlahBaris =tblBarang.getRowCount();
        return jumlahBaris;
    }
    
    private boolean cekBarisTerpilih(){
        return true;
    }

    private void KeyDelete() {
        baris = tblBarang.getSelectedRow();
        barisTerpilih=true;
        dataModel.removeRow(baris);
        
        total();
        clear();
        barisTerpilih=false;
    }
}

